project:
  type: website

website:
  title: "Paige Ann Carter"
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - href: about.qmd
        text: Current Research 
      - href: data.qmd
        text: Data Set 

format:
  html:
    theme:
      - litera
      - custom.scss
    css: styles.css
    toc: true



